import type {
  AutonomyPolicyOperator,
  ToolInvocation,
} from "@/types/autonomy-policies";

type PolicyDefinition = {
  argumentName: string;
  operator: AutonomyPolicyOperator.SupportedOperator;
  value: string;
  action: ToolInvocation.ToolInvocationPolicyAction;
  reason: string;
};

type PolicyPreset = Record<string, PolicyDefinition[]>;

// UUID regex pattern (matches standard UUID format)
const UUID_PATTERN =
  "[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}";

/**
 * Policy presets for different types of MCP servers.
 *
 * Structure:
 * - Key: preset name (e.g., "browser")
 * - Value: object mapping tool names to arrays of policies
 *   - "*" applies to all tools from that server
 *   - Specific tool names apply only to that tool
 */
export const POLICY_PRESETS: Record<string, PolicyPreset> = {
  browser: {
    // Global policy for all browser tools - validates session ID format
    "*": [
      {
        argumentName: "sessionId",
        operator: "regex",
        // Format: browser-{profileId}-{conversationId} where both are UUIDs
        // The dispatcher injects sessionId into tool arguments - agent never sees or handles this
        value: `^browser-${UUID_PATTERN}-${UUID_PATTERN}$`,
        action: "allow_when_context_is_untrusted",
        reason:
          "Allow browser tools with valid session format (generated by dispatcher)",
      },
    ],
    // SSRF protection for browser_navigate
    browser_navigate: [
      {
        argumentName: "url",
        operator: "regex",
        // Block internal network access and cloud metadata endpoints
        value:
          "(localhost|127\\.0\\.0\\.1|192\\.168\\.|10\\.|172\\.(1[6-9]|2[0-9]|3[01])\\.|\\[::1\\]|0\\.0\\.0\\.0|169\\.254\\.|metadata\\.google|metadata\\.aws)",
        action: "block_always",
        reason:
          "Block internal network and cloud metadata access (SSRF protection)",
      },
    ],
  },
};

/**
 * Get list of available policy preset names
 */
export function getAvailablePolicyPresets(): string[] {
  return Object.keys(POLICY_PRESETS);
}

/**
 * Get policy preset by name
 */
export function getPolicyPreset(name: string): PolicyPreset | undefined {
  return POLICY_PRESETS[name];
}

/**
 * Get policies for a specific tool from a preset.
 * Returns both global policies ("*") and tool-specific policies.
 */
export function getPoliciesForTool(
  presetName: string,
  toolName: string,
): PolicyDefinition[] {
  const preset = POLICY_PRESETS[presetName];
  if (!preset) return [];

  const globalPolicies = preset["*"] || [];
  const toolPolicies = preset[toolName] || [];

  return [...globalPolicies, ...toolPolicies];
}
